
name: prisma_HIP-based-policy-enforcement
label: Hip Enabled Security Policies for GlobalProtect
description: Prisma POC- addition to configure host information profile objects and profiles to be applied to policies.
# type of device configuration
type: panos
extends:

labels:
  collection:
    - GlobalProtect Basic

# variables used in the configuration templates
# type_hint defines the form field type in pan-cnc
variables:
  - name: HIP-CHECK-NAME
    description: What do you want to name the HIP object
    default: MacOS
    type_hint: text
  - name: HIP-PROFILE-NAME
    description: What do you want to name the HIP profile
    default: Is_Apple_Device
    type_hint: text
#  - name: TRUST-ZONE-NAME
#    description: What is the name of the Trust zone
#    default: GPCS_Mobile_trust
#    type_hint: text
#  - name: LOG-FILTER-NAME
#    description: What is the name of the log filter
#    default: GPCS-Mobile-Logging
#    type_hint: text
#  - name: SEC-RULE-NAME
#    description: Name of the security policy
#    default: Apple-Trust-to-Trust
#    type_hint: text

snippets:
  - name: hip_objects
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/hip-objects/
    file: 2-hip_objects.xml
  - name: hip_profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles/hip-profiles/
    file: 3-hip_profiles.xml
#  - name: gpcs_templates
#    xpath: /config/devices/entry[@name='localhost.localdomain']/template
#    file: gpcs_templates.xml
#  - name: gpcs_template_stacks
#    xpath: /config/devices/entry[@name='localhost.localdomain']/template-stack/entry
#    file: gpcs_template_stacks.xml
#  - name: mobile_user_devicegroup
#    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group
#    file: gpcs_devicegroup.xml
#  - name: hip_logs
#    xpath: /config/devices/entry[@name='localhost.localdomain']/template/entry[@name='Mobile_User_Template']/config/shared/log-settings/system/match-list/entry[@name='GPCS-Mobile-System']
#    file: 1-hip_logs.xml
#  - name: apply_to_sec_policies
#    xpath: /config/devices/entry[@name='localhost.localdomain']/device-group/entry[@name='{{ DEVICE-GROUP }}']/pre-rulebase/security/rules/entry
#    file: 4-apply_to_sec_policies.xml
